# thanks to: https://github.com/pybind/scikit_build_example

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.6.2",
    "cmake",
    "ninja",
    "numpy",	# necessary for scikit-build to work
    "scikit-build",
]

build-backend = "setuptools.build_meta"