# thanks to: https://github.com/pybind/scikit_build_example

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11~=2.6.0",
    "cmake",
    "ninja",
    "scikit-build",
]

build-backend = "setuptools.build_meta"